/*
 * MIT License
 *
 * Copyright (c) 2017-2018 Evan Hedbor
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.github.ehedbor.diskordlin.entities.channel

import com.beust.klaxon.Json
import io.github.ehedbor.diskordlin.entities.Snowflake
import io.github.ehedbor.diskordlin.entities.guild.GuildMember
import io.github.ehedbor.diskordlin.entities.user.Role
import io.github.ehedbor.diskordlin.entities.user.User

/**
 * Represents a message sent in a channel within Discord.
 *
 * Documentation copied from [here](https://discordapp.com/developers/docs/resources/channel).
 *
 * @property id id of the message
 * @property channelId id of the channel the message was sent in
 * @property guildId id of the guild the message was sent in
 * @property author the author of this message (not guaranteed to be a valid user)
 * @property member member properties for this message's author
 * @property content contents of the message
 * @property timestamp when this message was sent (ISO8601 timestamp)
 * @property editedTimestamp when this message was edited (or null if never) (ISO8601 timestamp)
 * @property tts whether this was a TTS message
 * @property mentionEveryone whether this message mentions everyone
 * @property mentions users specifically mentioned in the message
 * @property mentionRoles roles specifically mentioned in this message
 * @property attachments any attached files
 * @property embeds any embedded content
 * @property reactions reactions to the message
 * @property nonce used for validating a message was sent
 * @property pinned whether this message is pinned
 * @property webhookId if the message is generated by a webhook, this is the webhook's id
 * @property activity sent with Rich Presence-related chat embeds
 * @property application sent with Rich Presence-related chat embeds
 */
@Suppress("MemberVisibilityCanPrivate")
data class Message(
    val id: Snowflake,
    @Json("channel_id") val channelId: Snowflake,
    @Json("guild_id") val guildId: Snowflake?,
    val author: User,
    val member: GuildMember?,
    val content: String,
    val timestamp: String,
    @Json("edited_timestamp") val editedTimestamp: String? = null,
    val tts: Boolean = false,
    @Json("mention_everyone") val mentionEveryone: Boolean = false,
    val mentions: List<User> = emptyList(),
    @Json("mention_roles") val mentionRoles: List<Role> = emptyList(),
    val attachments: List<Attachment> = emptyList(),
    val embeds: List<Embed> = emptyList(),
    val reactions: List<Reaction> = emptyList(),
    val nonce: Snowflake? = null,
    val pinned: Boolean = false,
    @Json("webhook_id") val webhookId: Snowflake? = null,
    val type: Int,
    val activity: MessageActivity,
    val application: MessageApplication
)

object MessageType {
    const val DEFAULT = 0
    const val RECIPIENT_ADD = 1
    const val RECIPIENT_REMOVE = 2
    const val CALL = 3
    const val CHANNEL_NAME_CHANGE = 4
    const val CHANNEL_ICON_CHANGE = 5
    const val CHANNEL_PINNED_MESSAGE = 6
    const val GUILD_MEMBER_JOIN = 7
}

/**
 * Documentation copied from [here](https://discordapp.com/developers/docs/resources/channel).
 *
 * @property type type of message activity [MessageActivityType]
 * @property partyId party_id from a Rich Presence event
 */
data class MessageActivity(
    val type: Int,
    @Json("party_id") val partyId: String
)

/**
 * Documentation copied from [here](https://discordapp.com/developers/docs/resources/channel).
 *
 * @property id id of the application
 * @property coverImage id of the embed's image asset
 * @property description application's description
 * @property icon id of the application's icon
 * @property name name of the application
 */
data class MessageApplication(
    val id: Snowflake,
    @Json("cover_image") val coverImage: String,
    val description: String,
    val icon: String,
    val name: String
)

object MessageActivityType {
    val JOIN: Int = 1
    val SPECTATE: Int = 2
    val LISTEN: Int = 3
    val JOIN_REQUEST: Int = 4
}
